# CSE B4 - 221710304035 - MARRU RAHUL

In [0]:
import numpy as np

In [2]:
# Reversing an Array
arr1=np.arange(12,38)
print(arr1)
reverse=arr1[::-1]
print(reverse)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [3]:
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 
arr= np.ones((5,5))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
#Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
arr2= np.array([0, 10, 20, 40, 60])
print("array1: ",arr2)
arr3= [0, 40]
print("array2: ",arr3)
print(np.in1d(arr2, arr3))

array1:  [ 0 10 20 40 60]
array2:  [0, 40]
[ True False False  True False]


In [5]:
# Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

arr4 = np.array([0, 10, 20, 40, 60, 80])
print("array1: ",arr4)
arr5 = [10, 30, 40, 50, 70]
print("array2: ",arr5)
print(np.setdiff1d(arr4, arr5))

array1:  [ 0 10 20 40 60 80]
array2:  [10, 30, 40, 50, 70]
[ 0 20 60 80]


In [6]:
# Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's 
arr5= np.diagflat([4, 5, 6, 8])
print(arr5)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
